name: mongol_converter
description: "A Cyrillic to Mongolian converter"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mongol: ^9.0.0
  mongol_code: ^0.3.0
  pocketbase: ^0.22.0
  shared_preferences: ^2.5.2
  get_it: ^8.0.3
  package_info_plus: ^8.2.1
  file_saver: ^0.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MenksoftQagaan
      fonts:
        - asset: assets/fonts/MQG8F02.ttf
